"""add_embedding_kure

Revision ID: 02dbc7c4bb39
Revises: 2ff56110ce60
Create Date: 2026-02-07 22:59:30.775557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = '02dbc7c4bb39'
down_revision: Union[str, None] = '2ff56110ce60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('assets', sa.Column('embedding_kure', pgvector.sqlalchemy.Vector(1024), nullable=True, comment='Koure AI 임베딩 벡터 (1024차원)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'embedding_kure')
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
