"""add width height columns

Revision ID: 2ff56110ce60
Revises: ab3bcede9a4e
Create Date: 2026-02-06 16:54:09.905726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff56110ce60'
down_revision: Union[str, None] = 'ab3bcede9a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('width', sa.Integer(), nullable=True, comment='이미지 너비 (픽셀)'))
    op.add_column('assets', sa.Column('height', sa.Integer(), nullable=True, comment='이미지 높이 (픽셀)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'height')
    op.drop_column('assets', 'width')
    # ### end Alembic commands ###
