"""add_search_document

Revision ID: 42213168588e
Revises: 02dbc7c4bb39
Create Date: 2026-02-08 01:24:43.077817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42213168588e'
down_revision: Union[str, None] = '02dbc7c4bb39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('search_document', sa.Text(), nullable=True, comment='검색을 위한 문서화된 텍스트 (Vision LLM 생성 결과)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'search_document')
    # ### end Alembic commands ###
