"""Add error_message to assets

Revision ID: ab3bcede9a4e
Revises: e572cc226b72
Create Date: 2026-02-06 14:52:30.791125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab3bcede9a4e'
down_revision: Union[str, None] = 'e572cc226b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('error_message', sa.Text(), nullable=True, comment='작업 실패 시 에러 메시지'))
    op.alter_column('assets', 'id',
               existing_type=sa.INTEGER(),
               comment='에셋 고유 식별자 (Primary Key)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('assets', 'file_path',
               existing_type=sa.VARCHAR(),
               comment='생성된 에셋 파일의 저장 경로 (로컬 또는 S3)',
               existing_nullable=True)
    op.alter_column('assets', 'prompt',
               existing_type=sa.TEXT(),
               comment='에셋 생성에 사용된 텍스트 프롬프트',
               existing_nullable=False)
    op.alter_column('assets', 'model',
               existing_type=sa.VARCHAR(),
               comment='사용된 AI 모델명 (예: imagen-3.0-fast-generate-001, veo-3.0-fast-generate-001)',
               existing_nullable=False)
    op.alter_column('assets', 'asset_type',
               existing_type=postgresql.ENUM('IMAGE', 'VIDEO', name='assettypedb'),
               comment='에셋 타입: IMAGE(이미지) 또는 VIDEO(비디오)',
               existing_nullable=False)
    op.alter_column('assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='에셋 레코드 생성 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assets', 'job_id',
               existing_type=sa.VARCHAR(),
               comment='비동기 작업 추적을 위한 고유 작업 ID (UUID)',
               existing_nullable=False)
    op.alter_column('assets', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'),
               comment='작업 상태: PENDING(대기) -> PROCESSING(처리중) -> COMPLETED(완료) 또는 FAILED(실패)',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::jobstatus"))
    op.alter_column('assets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='에셋 레코드 최종 수정 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='에셋 레코드 최종 수정 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assets', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'),
               comment=None,
               existing_comment='작업 상태: PENDING(대기) -> PROCESSING(처리중) -> COMPLETED(완료) 또는 FAILED(실패)',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::jobstatus"))
    op.alter_column('assets', 'job_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='비동기 작업 추적을 위한 고유 작업 ID (UUID)',
               existing_nullable=False)
    op.alter_column('assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='에셋 레코드 생성 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assets', 'asset_type',
               existing_type=postgresql.ENUM('IMAGE', 'VIDEO', name='assettypedb'),
               comment=None,
               existing_comment='에셋 타입: IMAGE(이미지) 또는 VIDEO(비디오)',
               existing_nullable=False)
    op.alter_column('assets', 'model',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='사용된 AI 모델명 (예: imagen-3.0-fast-generate-001, veo-3.0-fast-generate-001)',
               existing_nullable=False)
    op.alter_column('assets', 'prompt',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='에셋 생성에 사용된 텍스트 프롬프트',
               existing_nullable=False)
    op.alter_column('assets', 'file_path',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='생성된 에셋 파일의 저장 경로 (로컬 또는 S3)',
               existing_nullable=True)
    op.alter_column('assets', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='에셋 고유 식별자 (Primary Key)',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('assets', 'error_message')
    # ### end Alembic commands ###
